# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_member_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(default=b'', max_length=40),
        ),
    ]
